/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/scene.gltf
Author: EWTube0 (https://sketchfab.com/EWTube0)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/batman-arkham-city-batman-hd-4f41e7625c9045bfb830fff50625ee56
Title: Batman Arkham City: Batman HD
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

const Batman = (props) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('./models/scene.gltf');
  const { actions, names } = useAnimations(animations, group);
  console.log(actions);
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Model001_Material001} castShadow/>
        <mesh geometry={nodes.Object_3.geometry} material={materials.Model001_Material002} castShadow/>
        <mesh geometry={nodes.Object_4.geometry} material={materials.Model001_Material003} castShadow/>
        <mesh geometry={nodes.Object_5.geometry} material={materials.Model001_Material004} castShadow/>
        <mesh geometry={nodes.Object_6.geometry} material={materials.Model001_Material005} castShadow/>
        <mesh geometry={nodes.Object_7.geometry} material={materials.Model001_Material006} castShadow/>
        <mesh geometry={nodes.Object_8.geometry} material={materials.Model001_Material007} castShadow/>
        <mesh geometry={nodes.Object_9.geometry} material={materials.Model001_Material008} castShadow/>
        <mesh geometry={nodes.Object_10.geometry} material={materials.Model001_Material009} castShadow/>
        <mesh geometry={nodes.Object_11.geometry} material={materials.Model001_Material010} castShadow/>
        <mesh geometry={nodes.Object_12.geometry} material={materials.Model001_Material011} castShadow/>
        <mesh geometry={nodes.Object_13.geometry} material={materials.Model001_Material012} castShadow/>
        <mesh geometry={nodes.Object_14.geometry} material={materials.Model001_Material013} castShadow/>
        <mesh geometry={nodes.Object_15.geometry} material={materials.Model001_Material014} castShadow/>
        <mesh geometry={nodes.Object_16.geometry} material={materials.Model001_Material015} castShadow/>
      </group>
    </group>
  )
}

export default Batman; 

useGLTF.preload('./models/scene.gltf')
